server:
  port: 8080
spring:
  application:
    name: mudancas-ap
  data:
    mongodb:
      #authentication-database: admin
      uri: mongodb://root:example@localhost:27017/mudanca?authSource=admin&authMechanism=SCRAM-SHA-256
      #uri: mongodb://root:example@localhost:27017/tech-challenge-orders?authSource=admin&replicaSet=myRepl
      #host: localhost
      # port: 27017
      # database: mudanca
      # username: root
      # password: example
